### ISSUE TITLE
MongoDB startup check is fragile (no-host mode), breaks with Homebrew's mongod

### ISSUE THREAD

**Issue by instanceofme** [deployd/deployd#229]
## Problem

With some `mongod` installations (such as Homebrew's), `dpd` will correctly start `mongod` but then hang.

## Cause

`lib/util/mongod.js` [uses the output](/deployd/deployd/blob/8d3d7a09f7d5134f7ab869fc5d06aa52e8d3ade4/lib/util/mongod.js#L38-40) from the `mongod` command and waits for the `waiting for connections` message. this assumes that `mongod` logs in stdout and not in a log file.

This isn't necessarily the case, particularly with [Homebrew's take](/mxcl/homebrew/blob/d0cc30c0c122cb5f889b1b432bfb03cee1d0f1be/Library/Formula/mongodb.rb#L32-36) on the `mongod` command:

```
#!/usr/bin/env ruby
ARGV << '--config' << '#{etc}/mongod.conf' unless ARGV.find { |arg|
arg =~ /^\s*\-\-config$/ or arg =~ /^\s*\-f$/
}
exec "#{prefix}/mongod", *ARGV
```

By default (unless another `--config`/`-f` argument is specified) it appends an `--config` argument to a config file that [redirects the log to a file](/mxcl/homebrew/blob/d0cc30c0c122cb5f889b1b432bfb03cee1d0f1be/Library/Formula/mongodb.rb#L48).

The result is that while `mongod` is launched and ready, dpd indefinitely waits for an output that will never come. This explains [some comments of] #203.

## Workarounds

Pick one, from cleanest to easiest:

- Launch `mongod` separately and use host mode; or
- Find the path to the original `mongod` binary (in the last line of `/usr/local/bin/mongod` for Homebrew) and call `dpd -m <path>`
- Manually patch `/path/to/node_modules/deployd/lib/util/mongod.js` and append `'-f', '/dev/null'` to the [`options` array](/deployd/deployd/blob/8d3d7a09f7d5134f7ab869fc5d06aa52e8d3ade4/lib/util/mongod.js#L26)

## Solution

The last solution can be adapted to fix this bug for the Homebrew case (or other installations that might work similarly). One would need to find a cross-platform solution though, not sure about `/dev/null` on Windows. Any empty file would do.

A more robust solution would be not to depend on output from `mongod` to observe that it has started. I realize that building the client object and trying to connect would require a refactoring, but that may be the cleanest option.

**Comment by ericfong** [comment]
I think this bug have been fixed. I close this first. Feel free to re-open it.

**Comment by visikolkar** [comment]
Hey Guys, I followed the above work around but seems like my mac still get the error. When I run the 
dpd  -d it opens the localhost but if I try to add the collections object, then the safari throws me an error i.e. Safari can't connect to the server. Please tell me where did I go wrong?
