### ISSUE TITLE
Failed to parse body as application/json

### ISSUE THREAD

**Issue by zimt28** [deployd/deployd#239]
Whenever I try to POST or PUT data, I get an error: Failed to parse body as application/json

**Comment by NicolasRitouet** [comment]
Old issue, probably solved by the many PR we have since then.

Feel free to reopen it of necessary.

**Comment by vvs4dev** [comment]
I face the issue still now... I am using win10..  Please will anyone be able to post the solution here..

**Comment by rgolea** [comment]
@vvs4dev it depends on how you send the query. Make sure you have your headers set properly and that you're sending a valid json.
