### ISSUE TITLE
emitToAll via internal-client should work

### ISSUE THREAD

**Issue by rngadam** [deployd/deployd#253]
This was posted at the end of issue #120 after it was closed and I believe it's still a real issue:

> Also, calls made via dpd (via internal-client), throw error while trying to emit event > as there is no session. 
> e.g.
> emit('object.updated', this);
> 
> fail. While its understandable that there is no session, but emitToAll should still be > able to publish the event.

In addition, there's a couple places where the code doesn't check for a session object to exist before trying to call emitToAll.

In the following, ```if(session.emitToAll)```  should be changed to ```if(session && session.emitToAll)```

```
$ grep -r "emitToAll" *
node_modules/deployd/lib/resources/collection/index.js:      if(session.emitToAll) session.emitToAll(collection.name + ':changed');
node_modules/deployd/lib/resources/collection/index.js:          if(session && session.emitToAll) session.emitToAll(collection.name + ':changed');
node_modules/deployd/lib/resources/collection/index.js:        if(session && session.emitToAll) session.emitToAll(collection.name + ':changed');
node_modules/deployd/lib/resources/collection/index.js:      if(session && session.emitToAll) session.emitToAll(collection.name + ':changed');
node_modules/deployd/lib/script.js:        if(session.emitToAll) session.emitToAll(event, data);
node_modules/deployd/lib/session.js:  this.emitToAll = function() {
```
which given this line in the On Post:

```
emit('emails:create', this);
```
will cause this line to be emitted:

```
DEBUG: {"message":"Cannot read property 'emitToAll' of undefined","status":400
```

You can't login from an internal client either to get around the lack of session:

```
{"message":"resource not found","status":404}
```

**Comment by losttime** [comment]
I ran into this same issue. Is there a workaround?

**Comment by andreialecu** [comment]
@losttime Could you provide a test case showing this?

**Comment by losttime** [comment]
I'll try to create write something programmatic, but since it's something that uses the internal-client, it's will probably take some time (as described here https://github.com/deployd/deployd/blob/master/test/internal-client.unit.js)

For the time being, here's what I'm doing:

I'm running deployd as a node module. My app wants to update one of the resources, so it calls `put()` from the internal-client`. The resource updates just fine, but I get an error just like @rngadam mentioned:

```
DEBUG: {"message":"Cannot read property 'emitToAll' of undefined","status":400}
```

I'm using deployd version 0.8.0
I'm running node 0.10.28
I'm running on a RaspberryPi
I'm running with `sudo` (due to requirements of other modules)

**Comment by losttime** [comment]
Correction, my error message is slightly different (didn't notice before).

```
{"message":"Cannot call method 'emitToUsers' of undefined","status":400}
```

**Comment by losttime** [comment]
I got it working. I had to supply a `session` when creating my `internal-client`.

It went something like this:

```js
var deployd = require('deployd');

var resourceId = 'fakeResourceId';
var state = 1;
var server = deployd();

server.on('listening', function() {
	var sessionStore = server.sessions;
	sessionStore.createSession(function(error, createdSession) {
		var dpdClient = internalClient.build(server, createdSession);
		dpdClient.resource.put(resourceId, {state: state}, function(result, error) {
			console.log('result', result, error);
		});
	});
});
```

The session is optional when creating an instance of the `internal-client`, but it's required if you want to be able to `emit()` events to your users over websockets when the internal-client changes anything.

Seems like an odd requirement to have, but at least it works.

**Comment by andreialecu** [comment]
@losttime I see, you are using the internal client from actual node code outside of the deployd realm. I don't think that's fully supported. Internal client is mainly for `dpd.collection` calls from internal resource scripts.

Care to explain why you need to use it like this? Maybe there's a better way.

**Comment by losttime** [comment]
My application interacts with the GPIO pins on the RaspberryPi. I need to update resources data based on what happens with the GPIO pins, so I'm starting an internal client instead of having the app make REST calls to itself.

My code is actually more like this:

```
var deployd = require('deployd');
var internalClient = require('deployd/lib/internal-client');
var Gpio = require('onoff').Gpio;

var resourceId = 'fakeResourceId';
var state = 1;
var server = deployd();
var dpdClient;
var gpioInput = new Gpio(4, 'in', 'both');

server.on('listening', function() {
    var sessionStore = server.sessions;
    sessionStore.createSession(function(error, createdSession) {
        dpdClient = internalClient.build(server, createdSession);
    });
});

gpioInput.watch(function(err, value) {
    if (dpdClient) {
        dpdClient.resource.put(resourceId, {state: value}, function(result, error) {
            console.log('result', result, error);
        });
    }
});
```

I'm running the app basically as a custom run script (http://docs.deployd.com/docs/server/run-script.html). Is there a better way to run custom code alongside the standard REST/websocket server created by deployd?

**Comment by ericfong** [comment]
Can I consider this issue is fixed?  I think this is advanced usage.

**Comment by n321203** [comment]
Fyi, this issue is still present (v 0.8.4). Here's a test case: 

1. Create a custom module:

```
var Resource = require('deployd/lib/resource')
    , util = require('util')
    , internalClient = require('deployd/lib/internal-client')


function Hello(name, options) {
    Resource.apply(this, arguments);
}
util.inherits(Hello, Resource);
module.exports = Hello;

Hello.prototype.clientGeneration = true;

Hello.prototype.handle = function (ctx, next) {
    if(ctx.req && ctx.req.method !== 'GET') return next();

		var dpd = internalClient.build(process.server);
		dpd.orders.put( "document_id_to_update", {status:"updated!"}, function(result, err){
			console.log(result, err)
		})

    ctx.done(null, {hello: 'world'});
}
```

2. Issue a GET request to /hello

Result: '{"message":"Cannot read property \'emitToAll\' of undefined","status":400}'

**Comment by n321203** [comment]
Actually, a sessions is not needed – an empty object at creation will make the error go away!
If
```
        var dpd = internalClient.build(process.server);
```
is changed to
```
        var dpd = internalClient.build(process.server, {});
```
in the example above, the error goes away!
