### ISSUE TITLE
New cookies auth throw exception

### ISSUE THREAD

**Issue by ipepe** [deployd/deployd#551]
My deployd version is newest master branch
I have application and i use dpd-event to login user with simple http form. This is code inside my dpd-event ON POST event:
```javascript
if( typeof parts !== 'undefined' ){
    switch(parts[0]){
        case 'userLogin':
            dpd.users.login({username: body.username, password: body.password}, function(result,error){
                ctx.res.statusCode = 302;
                ctx.res.setHeader('Location', 'http://' + ctx.req.headers['host'] );
            });
            break;
        default:
            break;
    }
}
```
html/form
```html
<form class="pure-form" action="/actions/userLogin" method="post" >
    <input name="username" type="email" placeholder="email" required="required">
    <br>
    <input name="password" type="password" placeholder="password" pattern=".{8,}" required title="min 8 chars">
    <br>
    <button type="submit">Confirm</button>
</form>
```

This is my error in console:
```
TypeError: Cannot read property 'set' of undefined
    at /Users/.../nodeProjects/.../node_modules/deployd/lib/resources/user-collection.js:210:26
```

And this is code snip that is problematic:
```javascript
    function loginDone(err) {
      if (err) return ctx.done(err);
      checkAndSaveUser(function (err) {
        if (err) return ctx.done(err);
        debug('logged in as %s', credentials.username);
        ctx.session.set({ path: path, uid: user.id, userhash: usernameAndPasswordHash }).save(function (err, session) {
          if (err) return ctx.done("Internal error");
          //here cookies doesnt exist in ctx.res
          ctx.res.cookies.set('sid', session.id, { overwrite: true });
          ctx.done(err, { path: session.path, id: session.id, uid: session.uid });
        });
      });
    }
```

**Comment by ipepe** [comment]
blame on @andreialecu in https://github.com/deployd/deployd/commit/26b9448ee4c89d4ce5d5b4f1b5eb30b99a125873

**Comment by andreialecu** [comment]
Reason for this is that the internal client doesn't have `req.cookies`. Ref: https://github.com/deployd/deployd/blob/master/lib/internal-client.js#L72

A simple check for 
`if (ctx.res.cookies) ` before line 210 should fix this. I'm working on a test and will submit PR.

**Comment by andreialecu** [comment]
Fixed in #552. Part of this passing unnoticed is that one of the tests was broken and not really testing anything. I have improved that test to detect this and potentially other problems.

Thanks for the report @ipepe.

**Comment by andreialecu** [comment]
Merged. Closing. Feel free to reopen if you have further issues with this.

**Comment by ipepe** [comment]
It still doesn't work for me. Do You want me to create repository with app that will have this problem?

**Comment by ipepe** [comment]
i created repo that will help You reproduce problem: https://github.com/ipepe/deployd-login-bug

**Comment by andreialecu** [comment]
That is by design.

You are calling `dpd.users.login` from an event script. there is no correlation between that and the cookies that are set by your event script. If you want to forward the cookies onwards you need to do something like this: (untested, try it)

```
if( typeof parts !== 'undefined' ){
    switch(parts[0]){
        case 'userLogin':
            dpd.users.login({username: body.username, password: body.password}, function(result,error){
                ctx.res.statusCode = 302;
                ctx.res.cookies.set('sid', result.id, { overwrite: true }); // add this
                ctx.res.setHeader('Location', 'http://' + ctx.req.headers['host'] );
            });
            break;
        default:
            break;
    }
}
```

**Comment by ipepe** [comment]
You are right. That works fine! Thank You.
